version: '3'
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=${DB}
    volumes:
      - "./ny_taxi_psgres_data:/var/lib/postgresql/data:rw"
    ports: 
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  taxi_ingest:
    build: ./
    environment:
      - URL=${URL}
      - TBNAME=${TBNAME}
      - DB=${DB}
    command: --user=root --password=root --host=pgdatabase --port=5432 --db=${DB} --table_name=${TBNAME} --url=${URL}
    depends_on:
      - pgdatabase